name: {{PROJECT_NAME}}
options:
  bundleIdPrefix: {{BUNDLE_ID_ROOT}}
  developmentLanguage: en
  deploymentTarget:
    iOS: "{{DEPLOYMENT_TARGET}}"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

# packages:
  # Add Swift Package Manager dependencies here when needed
  # Example:
  # Alamofire:
  #   url: https://github.com/Alamofire/Alamofire
  #   majorVersion: 5.8.0

settings:
  base:
    # Swift version
    SWIFT_VERSION: "{{SWIFT_VERSION}}"
    # Development settings
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "Apple Development"
    CODE_SIGN_STYLE: Automatic
    # Build settings
    ENABLE_BITCODE: false
    SUPPORTS_MACCATALYST: false
    # Warning settings
    SWIFT_TREAT_WARNINGS_AS_ERRORS: false
    GCC_TREAT_WARNINGS_AS_ERRORS: false
    # Other settings
    ENABLE_HARDENED_RUNTIME: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    STRING_CATALOG_GENERATE_SYMBOLS: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  {{PROJECT_NAME}}:
    type: application
    platform: iOS
    deploymentTarget: "{{DEPLOYMENT_TARGET}}"
    sources:
      - {{PROJECT_NAME}}
    resources:
      - {{PROJECT_NAME}}/Resources
    info:
      path: {{PROJECT_NAME}}/Info.plist
      properties:
        CFBundleDisplayName: {{PROJECT_NAME}}
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - armv7
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate

  {{PROJECT_NAME}}Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "{{DEPLOYMENT_TARGET}}"
    sources:
      - {{PROJECT_NAME}}Tests
    dependencies:
      - target: {{PROJECT_NAME}}

  {{PROJECT_NAME}}UITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "{{DEPLOYMENT_TARGET}}"
    sources:
      - {{PROJECT_NAME}}UITests
    dependencies:
      - target: {{PROJECT_NAME}}

schemes:
  {{PROJECT_NAME}}:
    build:
      targets:
        {{PROJECT_NAME}}: all
        {{PROJECT_NAME}}Tests: [test]
        {{PROJECT_NAME}}UITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - {{PROJECT_NAME}}
      targets:
        - {{PROJECT_NAME}}Tests
        - {{PROJECT_NAME}}UITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
