name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Shell Scripts
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Run shellcheck
        run: ./scripts/lint.sh

  format:
    name: Check Formatting
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shfmt
        run: brew install shfmt

      - name: Check formatting
        run: ./scripts/format.sh

  validate:
    name: Validate YAML
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yq
        run: brew install yq

      - name: Validate YAML files
        run: ./scripts/validate.sh

  test:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install shellcheck shfmt yq

      - name: Run test suite
        run: ./scripts/test.sh

  integration:
    name: Integration Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run integration test suite
        run: ./scripts/integration-test.sh
